[project]
name = "snowflake"
version = "1.0"
description = ""
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
]


[project.scripts]
snowflake = "snowflake.main:main_func"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

