[project]
name = "snowflake"
version = "1.0"

[project.scripts]
snowflake = "snowflake:main_func"



[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["snowflake"]
